### ISSUE TITLE
issue on mustache.js

### ISSUE THREAD

**Issue by dipenpatel235** [juho-jaakkola/elgg-live_chat#1]
Hello
I have try to install live_chat plugin but getting below error
Can you Know how to fix below error ?

[root@localhost live_chat]# php /usr/bin/composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/mustache.js could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Thanks
Dipen Patel

**Comment by juho-jaakkola** [comment]
As mentioned via email, you first need to install the `composer-asset-plugin`:

```
php /usr/bin/composer.phar global require "fxp/composer-asset-plugin:~1.1.1"
```
