### ISSUE TITLE
Not Working Live chat

### ISSUE THREAD

**Issue by dipenpatel235** [juho-jaakkola/elgg-live_chat#2]
Here i attached screen shot..

Bottom of page Seen Below User interface By Activating live_chat plugin...
So it is correct interface or any issue from my sides ?
because looking something wired....and also not able to chat....
Thanks

![untitled](https://cloud.githubusercontent.com/assets/8135097/12807573/f0489684-cb35-11e5-9a65-429dfd04b27c.png)

**Comment by juho-jaakkola** [comment]
Which Elgg version are you using?

**Comment by dipenpatel235** [comment]
i am using elgg 1.11

**Comment by juho-jaakkola** [comment]
I haven't tested it on Elgg 1.x. Most likely some of the features work only on Elgg 2.

I don't think I will be adding support for Elgg 1.x at all. It's time to upgrade to Elgg 2.
